### ISSUE TITLE
Replace the default repository to main

### ISSUE THREAD

**Issue by ruimartinsptl** [docat-org/docat-helm#2]
Sorry, by mistake I created the first branch with a name different from `main`, and now the default branch is not the `main`, can you change the settings, please? And set `main` as the default branch.

|![Screenshot 2023-09-25 at 01 42 00](https://github.com/docat-org/docat-helm/assets/2766648/a0b1b3df-c696-46c4-988e-d047d610d583)|
|-

Thanks

**Comment by fliiiix** [comment]
no worries -> Default branch changed to main
